const mockStore = {
  user: {
    id: "demo-alex-id",
    email: "alex.rivera@synexora.io",
    fullName: "Alex Rivera",
    role: "ROLE_STUDENT",
    major: "Computer Science & Engineering",
    academicYear: "Year 3",
    gpa: 3.85,
    masteryScore: 84.0,
    studyStreakDays: 14,
    learningStylePreference: "Interactive Code Traces & Socratic Hints",
  },
  memories: [
    {
      id: "mem-1",
      category: "Academic Performance",
      title: "DBMS Midterm Score",
      value: "72/100 (Target: 85%+ in Final Exam)",
      confidenceScore: 0.98,
      isConfirmed: true,
      isSensitive: false,
      sourceContext: "Midterm Assessment Dialogue",
      createdAt: new Date().toISOString(),
    },
    {
      id: "mem-2",
      category: "Important Dates",
      title: "Distributed Systems Project Submission",
      value: "Friday Final Submission at 23:59",
      confidenceScore: 0.99,
      isConfirmed: true,
      isSensitive: false,
      sourceContext: "Syllabus Extraction",
      createdAt: new Date().toISOString(),
    },
    {
      id: "mem-3",
      category: "Learning Style",
      title: "Explanation Format Preference",
      value: "Prefers step-by-step Socratic hints over plain textbook answers",
      confidenceScore: 0.94,
      isConfirmed: true,
      isSensitive: false,
      sourceContext: "Student Persona Configuration",
      createdAt: new Date().toISOString(),
    },
  ],
  tasks: [
    {
      id: "task-1",
      title: "Submit Distributed Systems Project Draft",
      courseCode: "CS301",
      status: "TODO",
      priority: "HIGH",
      dueDate: new Date(Date.now() + 2 * 86400000).toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: "task-2",
      title: "Complete BCNF Normalization Practice Set",
      courseCode: "CS220",
      status: "TODO",
      priority: "HIGH",
      dueDate: new Date(Date.now() + 1 * 86400000).toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: "task-3",
      title: "Review Bellman-Ford Shortest Path Proof",
      courseCode: "CS240",
      status: "DONE",
      priority: "MEDIUM",
      dueDate: new Date(Date.now() - 1 * 86400000).toISOString(),
      createdAt: new Date().toISOString(),
    },
  ],
  notes: [
    {
      id: "note-1",
      title: "BFS vs DFS Queue Invariants",
      courseCode: "CS240",
      content: "BFS uses FIFO Queue ensuring level-by-level traversal. DFS uses LIFO Stack exploring deep branches first.",
      isAiSuggested: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: "note-2",
      title: "Raft Consensus Key Principles",
      courseCode: "CS301",
      content: "Leader Election: randomized election timers prevent split votes. Log Replication: Leader broadcasts AppendEntries RPCs.",
      isAiSuggested: false,
      createdAt: new Date().toISOString(),
    },
  ],
  calendarEvents: [
    {
      id: "event-1",
      title: "CS301 Lecture: Raft Consensus Algorithm",
      eventType: "LECTURE",
      roomLocation: "Hall B",
      startTime: new Date(Date.now() + 3 * 3600000).toISOString(),
      endTime: new Date(Date.now() + 5 * 3600000).toISOString(),
    },
    {
      id: "event-2",
      title: "Synexora Scheduled Study: B-Tree Indexing",
      eventType: "AI_STUDY_BLOCK",
      roomLocation: "Library",
      startTime: new Date(Date.now() + 6 * 3600000).toISOString(),
      endTime: new Date(Date.now() + 8 * 3600000).toISOString(),
    },
  ],
  goals: [
    {
      id: "goal-1",
      title: "Achieve 85%+ in DBMS Final Exam",
      targetDate: new Date(Date.now() + 60 * 86400000).toISOString(),
      progressPercentage: 68,
      status: "IN_PROGRESS",
    },
    {
      id: "goal-2",
      title: "Complete Raft Implementation with 100% Test Pass",
      targetDate: new Date(Date.now() + 20 * 86400000).toISOString(),
      progressPercentage: 85,
      status: "IN_PROGRESS",
    },
  ],
};

module.exports = { mockStore };
